/*
 * Todo Manager API
 *
 * This is todo manager backend for coding tests.
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"context"
	"net/http"
	"errors"
)

// DefaultApiService is a service that implements the logic for the DefaultApiServicer
// This service should implement the business logic for every endpoint for the DefaultApi API.
// Include any external packages or services that will be required by this service.
type DefaultApiService struct {
}

// NewDefaultApiService creates a default api service
func NewDefaultApiService() DefaultApiServicer {
	return &DefaultApiService{}
}

// UsersPost - 
func (s *DefaultApiService) UsersPost(ctx context.Context, usersForReq UsersForReq) (ImplResponse, error) {
	// TODO - update UsersPost with the required logic for this service method.
	// Add api_default_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(200, UsersForRes{}) or use other options such as http.Ok ...
	//return Response(200, UsersForRes{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("UsersPost method not implemented")
}

// UsersUserIdDelete - 
func (s *DefaultApiService) UsersUserIdDelete(ctx context.Context, userId string) (ImplResponse, error) {
	// TODO - update UsersUserIdDelete with the required logic for this service method.
	// Add api_default_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(200, UsersForRes{}) or use other options such as http.Ok ...
	//return Response(200, UsersForRes{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("UsersUserIdDelete method not implemented")
}

// UsersUserIdGet - 
func (s *DefaultApiService) UsersUserIdGet(ctx context.Context, userId string) (ImplResponse, error) {
	// TODO - update UsersUserIdGet with the required logic for this service method.
	// Add api_default_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(200, UsersForRes{}) or use other options such as http.Ok ...
	//return Response(200, UsersForRes{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("UsersUserIdGet method not implemented")
}

// UsersUserIdPatch - 
func (s *DefaultApiService) UsersUserIdPatch(ctx context.Context, userId string, usersForReq UsersForReq) (ImplResponse, error) {
	// TODO - update UsersUserIdPatch with the required logic for this service method.
	// Add api_default_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(200, UsersForRes{}) or use other options such as http.Ok ...
	//return Response(200, UsersForRes{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("UsersUserIdPatch method not implemented")
}

// UsersUserIdPost - 
func (s *DefaultApiService) UsersUserIdPost(ctx context.Context, userId string, inlineObject InlineObject) (ImplResponse, error) {
	// TODO - update UsersUserIdPost with the required logic for this service method.
	// Add api_default_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(200, UsersForRes{}) or use other options such as http.Ok ...
	//return Response(200, UsersForRes{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("UsersUserIdPost method not implemented")
}

// UsersUserIdTasksGet - 
func (s *DefaultApiService) UsersUserIdTasksGet(ctx context.Context, userId string) (ImplResponse, error) {
	// TODO - update UsersUserIdTasksGet with the required logic for this service method.
	// Add api_default_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(200, []TasksForRes{}) or use other options such as http.Ok ...
	//return Response(200, []TasksForRes{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("UsersUserIdTasksGet method not implemented")
}

// UsersUserIdTasksPost - 
func (s *DefaultApiService) UsersUserIdTasksPost(ctx context.Context, userId string, tasksForReq TasksForReq) (ImplResponse, error) {
	// TODO - update UsersUserIdTasksPost with the required logic for this service method.
	// Add api_default_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(200, TasksForRes{}) or use other options such as http.Ok ...
	//return Response(200, TasksForRes{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("UsersUserIdTasksPost method not implemented")
}

// UsersUserIdTasksTaskIdDelete - 
func (s *DefaultApiService) UsersUserIdTasksTaskIdDelete(ctx context.Context, userId string, taskId string) (ImplResponse, error) {
	// TODO - update UsersUserIdTasksTaskIdDelete with the required logic for this service method.
	// Add api_default_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(200, {}) or use other options such as http.Ok ...
	//return Response(200, nil),nil

	return Response(http.StatusNotImplemented, nil), errors.New("UsersUserIdTasksTaskIdDelete method not implemented")
}

// UsersUserIdTasksTaskIdGet - 
func (s *DefaultApiService) UsersUserIdTasksTaskIdGet(ctx context.Context, userId string, taskId string) (ImplResponse, error) {
	// TODO - update UsersUserIdTasksTaskIdGet with the required logic for this service method.
	// Add api_default_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(200, TasksForRes{}) or use other options such as http.Ok ...
	//return Response(200, TasksForRes{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("UsersUserIdTasksTaskIdGet method not implemented")
}

// UsersUserIdTasksTaskIdPatch - 
func (s *DefaultApiService) UsersUserIdTasksTaskIdPatch(ctx context.Context, userId string, taskId string) (ImplResponse, error) {
	// TODO - update UsersUserIdTasksTaskIdPatch with the required logic for this service method.
	// Add api_default_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(200, TasksForRes{}) or use other options such as http.Ok ...
	//return Response(200, TasksForRes{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("UsersUserIdTasksTaskIdPatch method not implemented")
}
