/*
 * sample API
 *
 * This is sample.
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type Pets struct {

	Id int64 `json:"id,omitempty"`

	Name string `json:"name,omitempty"`

	// pet status in the store
	Status string `json:"status,omitempty"`
}

// AssertPetsRequired checks if the required fields are not zero-ed
func AssertPetsRequired(obj Pets) error {
	return nil
}

// AssertRecursePetsRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of Pets (e.g. [][]Pets), otherwise ErrTypeAssertionError is thrown.
func AssertRecursePetsRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aPets, ok := obj.(Pets)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertPetsRequired(aPets)
	})
}
