/*
 * Todo Manager API
 *
 * This is todo manager backend for coding tests.
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package main

import (
	"github.com/aws/aws-lambda-go/lambda"
	"log"
	"net/http"
	"os"

	openapi "github.com/GIT_USER_ID/GIT_REPO_ID/go"
)

var region = os.Getenv("AWS_REGION")

func functions() {
	log.Printf("Server started")

	DefaultApiService := openapi.NewDefaultApiService()
	DefaultApiController := openapi.NewDefaultApiController(DefaultApiService)

	router := openapi.NewRouter(DefaultApiController)

	log.Fatal(http.ListenAndServe(":8080", router))
}

func main() {
	if region != "" {
		lambda.Start(functions)
	}
	functions()
}
